version: "3.0"

services:
  app:
    restart: unless-stopped
    build: .
    volumes:
      - .:/code
    ports:
      - "8180:8180"
      - "8443:8443"
    environment:
      DB_HOST: 185.78.165.84
      DB_PORT: 3306
      DB_NAME: steve37db
      DB_USER: steve
      DB_PASSWORD: thrnnvtn
    
