services:
  app:
    restart: unless-stopped
    build: .
    volumes:
      - .:/code
      # Map logs directory to host filesystem
      # Create ./logs directory on host before running docker-compose
      - ./logs:/logs
    ports:
      - "8180:8180"
      - "8443:8443"
    # Use host networking to connect to MySQL service on the same server
    network_mode: "host"
    
